%YAML:1.0
# data
dataset_path: /media/lzb/Windows-SSD/ubuntu16/00

# ros stereo topics
left_image_topic: /zed/zed_node/left/image_rect_color
right_image_topic: /zed/zed_node/right/image_rect_color

# don't care，it doesn't effect others.(this param is diacard)
ros_data_IaE_dir: /

# ZED
# camera_L intrinsics
# camera_l.fx: 699.715
# camera_l.fy: 699.715
# camera_l.cx: 648.854
# camera_l.cy: 350.34

# camera_R intrinsics
# camera_r.fx: 699.39
# camera_r.fy: 699.39
# camera_r.cx: 645.379
# camera_r.cy: 365.323

# Extrinsics (t)
#Extrinsics_x: 0.12
#Extrinsics_y: 0.00
#Extrinsics_z: 0.00

# --------Sensors----------------
# Kitti
#camera_L intrinsics
camera_l.fx: 718.856
camera_l.fy: 718.856
camera_l.cx: 607.193
camera_l.cy: 185.216

# camera_R intrinsics
camera_r.fx: 718.856
camera_r.fy: 718.856
camera_r.cx: 607.193
camera_r.cy: 185.216

# t_rl_0.537
t_lr0: -0.537
t_lr1: 0.00
t_lr2: 0.00
# R_rl_
R_lr0: 1.0
R_lr1: 0.0
R_lr2: 0.0
R_lr3: 0.0
R_lr4: 1.0
R_lr5: 0.0
R_lr6: 0.0
R_lr7: 0.0
R_lr8: 1.0

#-----------Tracking------------------------
# feature detector
num_features: 500

# init
num_features_init: 20
init_landmarks: 5
feature_match_error: 3

# tracking
num_features_tracking: 5
num_features_tracking_bad: 10
num_features_needed_for_keyframe: 60


#you can choose LK_stereof2f_pnp, ORB_stereof2f_pnp
track_mode: ORB_stereof2f_pnp

inlier_rate: 0.01

# estimate pose cv::pnp_ransac
iterationsCount: 500
reprojectionError: 0.5
confidence: 0.99

display_scale: 1
display_x: 400
display_y: 200
minmove: 0.05
maxmove: 10
fMinThFAST: 7
fIniThFAST: 20
nLevels: 8
fScaleFactor: 1.2
nFeatures: 2000

