%YAML:1.0


# data
dataset_dir_kitti: /media/lzb/18829571198/common_datasets/kitti
dataset_dir_tum: /media/lzb/18829571198/common_datasets/euroc/MH_01_easy

# ros stereo topics

# camera intrinsics
camera.fx: 517.3
camera.fy: 516.5
camera.cx: 325.1
camera.cy: 249.7

# 
num_features: 150
num_features_init: 50
num_features_tracking: 50
