%YAML:1.0


# data
dataset_dir_kitti: /media/lzb/18829571198/common_datasets/kitti
dataset_dir_tum: /media/lzb/18829571198/common_datasets/euroc/MH_01_easy

# ros stereo topics
left_image_topic: /zed/zed_node/left/image_rect_color
right_image_topic: /zed/zed_node/right/image_rect_color

# don't care，it doesn't effect others.(this param is diacard)
ros_data_IaE_dir: /

# camera_L intrinsics
camera_l.fx: 699.715
camera_l.fy: 699.715
camera_l.cx: 648.854
camera_l.cy: 350.34

# camera_R intrinsics
camera_r.fx: 699.39
camera_r.fy: 699.39
camera_r.cx: 645.379
camera_r.cy: 365.323

# Extrinsics (t)
Extrinsics_x: 0.12
Extrinsics_y: 0.00
Extrinsics_z: 0.00
 

# feature detector
num_features: 150

# init
num_features_init: 30
init_landmarks: 5
feature_match_error: 40

# tracking
num_features_tracking: 30
num_features_tracking_bad: 10
num_features_needed_for_keyframe : 100